version: "3.8"
services:
  db:
    image: rethinkdb:${RETHINKDB_IMAGE_TAG:-2.3.7}
    restart: unless-stopped
    container_name: db
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    volumes:
      - db-data:/data
    networks:
      - classifier-pipeline-network
    command: ["rethinkdb", "--bind", "all", "--cache-size", "${RETHINKDB_CACHE_SIZE:-1024}"]
  dbbackup:
    image: pathwaycommons/rethinkdb-backup:${DBBACKUP_IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: dbbackup
    volumes:
      - db-archives:/home/appuser/app/archives
    depends_on:
      - db
    environment:
      DUMP_PATH:
      DB_HOST: "db"
      SYNC_ENABLED:
    networks:
      - classifier-pipeline-network

volumes:
  db-data:
  db-archives:

networks:
  classifier-pipeline-network:
    driver: bridge
